### ISSUE TITLE
Static Scenes/Thing 3D

### ISSUE THREAD

**Issue by dd2252** [naver/dust3r#104]
Hi and thanks for your awesome work! 

In the paper, one of the train datasets is Static Scenes 3D [68], which is referred to as Static Thing 3D [68] in the Supplemental. When I follow the link to this dataset, it appears to be from "A large dataset to train convolutional networks for disparity, optical flow, and scene flow estimation," which introduces the datasets FlyingThings3D, Monkaa, and Driving. 
- These all are highly dynamic datasets, violating the assumptions of 3D correspondence used for DUST3R. Is this the correct dataset? 
- If so, is there some modification to the data, or how does the model handle moving objects? Does it impact trained model performance?

Thank you!

**Comment by yocabon** [comment]
Hi, I think the citation for static things 3D is incorrect. We had a bit difficulty finding the original source for this one. Anyway, it's from here: https://github.com/lmb-freiburg/robustmvd/blob/master/rmvd/data/README.md#staticthings3d
