### ISSUE TITLE
About depthmap when training

### ISSUE THREAD

**Issue by wuqun-tju** [naver/dust3r#121]
Thank you for your work!
I wonder if I use my own dataset , how to normalize depthmap,
I found in co3d.py , you normalize them using
" depthmap = (depthmap.astype(np.float32) / 65535) * 
  np.nan_to_num(input_metadata['maximum_depth']) "

Otherwise, if I have sparse depthmap generated from Lidar, can it work  on dust3r network?

Lookingforward your reply!

**Comment by yocabon** [comment]
see https://github.com/naver/dust3r/issues/105#issuecomment-2106798157
there's no need to normalize the depthmap at the dataset level. the best is to keep it to whatever it is.
