### ISSUE TITLE
Where to Obtain Precomputed Pairs 

### ISSUE THREAD

**Issue by zjrandom951** [naver/dust3r#131]
Hello,

I am currently working on a project that requires the use of precomputed pairs. Could you please provide information on where I can find or how I can generate these precomputed pairs? Any guidance or resources would be greatly appreciated.

Thank you!
![image](https://github.com/naver/dust3r/assets/67944280/8d12eb7b-c957-4169-9c80-59b78e8a02b1)

**Comment by yocabon** [comment]
Hi,
there are listed in the readme
https://github.com/naver/dust3r?tab=readme-ov-file#datasets

Links:

[ARKitScenes pairs](https://download.europe.naverlabs.com/ComputerVision/DUSt3R/arkitscenes_pairs.zip)
[ScanNet++ pairs](https://download.europe.naverlabs.com/ComputerVision/DUSt3R/scannetpp_pairs.zip)
[BlendedMVS pairs](https://download.europe.naverlabs.com/ComputerVision/DUSt3R/blendedmvs_pairs.npy)
[WayMo Open dataset pairs](https://download.europe.naverlabs.com/ComputerVision/DUSt3R/waymo_pairs.npz)
[Habitat metadata](https://download.europe.naverlabs.com/ComputerVision/DUSt3R/habitat_5views_v1_512x512_metadata.tar.gz)
[MegaDepth pairs](https://download.europe.naverlabs.com/ComputerVision/DUSt3R/megadepth_pairs.npz)
[StaticThings3D pairs](https://download.europe.naverlabs.com/ComputerVision/DUSt3R/staticthings_pairs.npy)

**Comment by zjrandom951** [comment]
Thank you for your prompt response and for providing the link.

I have found the information regarding the precomputed pairs in the README file as you mentioned. This is very helpful for my project.

Thanks again for your assistance!

**Comment by nobeldang** [comment]
Hi, thanks for sharing your work. While I can find the arkitscene's selected_pairs.npz I was wondering how you created those npy files. If you can provide some script on how you matched the lowres_wide.traj information (poses) with the RGB files selected that would be great.

Thanks!
