### ISSUE TITLE
Q about Absolute pose estimation

### ISSUE THREAD

**Issue by TwiceMao** [naver/dust3r#136]
Thx for your awesome work!  @yocabon @beanmilk @seyoung-hyun 
![image](https://github.com/naver/dust3r/assets/43490149/b200a028-fd3d-4b6d-ad92-e37e2c8e3c8a)

**Comment by TwiceMao** [comment]
Additionally, I have questions about "Global Optimization" and "Recovering Camera Parameters." In Equation (5) of the main paper, how is $\chi^{v}_{i}$ obtained?I speculate that it involves first estimating the intrinsics for each image, then using the z-coordinates of the point map corresponding to each RGB image in the camera coordinate system as the depth. And the depth  is utilized in the below equation as $D_{i,j}^{n}$
![image](https://github.com/naver/dust3r/assets/43490149/554b7f43-7a88-47da-8757-8b0a010a9c09)

Could you please provide the initial values for  $P_e, \sigma_e $  and the scale factor?

**Comment by yocabon** [comment]
Hi,
First question about visual localization, $I_B$ is the database images, so its pose, intrinsics and 2D-3D correspondences are known (part of the SfM map).

Second question, did you check the code of the global optimizer ?
initialization: https://github.com/naver/dust3r/blob/main/dust3r/cloud_opt/init_im_poses.py#L123
optimization: https://github.com/naver/dust3r/blob/main/dust3r/cloud_opt/optimizer.py

**Comment by TwiceMao** [comment]
Thank you for your kind response~
