### ISSUE TITLE
The output depthmap of model is metric depth or relative?

### ISSUE THREAD

**Issue by puyiwen** [naver/dust3r#145]

**Comment by puyiwen** [comment]
well, I found the output of DPT model is not metric depth, while the output of Linear model seems to be metric depth. Am I right?

**Comment by zcczhang** [comment]
Also a maybe related question: the mast3r depth is metric right

**Comment by puyiwen** [comment]
@zcczhang I find the depth map of dust3r is not metric, but I use `scale*relavtive depth + shift` to get metric depth, the result of NYUv2 is better than paper, I dont know why. I also run the mast3r to get depthmap, I use `get_depthmap()` function, however, the size of output is not true. For example, RGB size is (512, 384), the output size of model is (512, 384), and then the depthmap size is (3172,). Am I doing something wrong?
