### ISSUE TITLE
Questions about the code

### ISSUE THREAD

**Issue by wdkkkk** [naver/dust3r#149]
Hello,

After reading through your code, I have a few questions. In your paper, you mentioned that:
 
![image](https://github.com/user-attachments/assets/c0c9560b-68d7-4cd7-b6be-3992a6b40bb5)

This can be understood as decoder1 being responsible for outputting the pointmaps of view 1 (while referencing information from view 2 in the process); for decoder2, it is the opposite.

However, in your code, at the end of the encoder module, you use a function named "interleave":

![image](https://github.com/user-attachments/assets/c7dc239a-e24f-4f25-b31c-dcd2120b2367)

This function takes $F^1$ and $F^2$ as input and outputs $feat1 = [F^1, F^2]$ and $feat2 = [F^2, F^1]$ (I used lists here to represent the batch dimension of tensors).  So in this implementation, the formulation of the decoder would becomes:

$$
[G_i^{1}, G_i^{1}] = DecoderBlock_i^1([G_{i-1}^{1}, G_{i-1}^{1}], [G_{i-1}^{2*}, G_{i-1}^{1*}] ) , 
$$

$$
[G_i^{2*}, G_i^{1*}] = DecoderBlock_i^2([G_{i-1}^1, G_{i-1}^2], [G_{i-1}^{2*}, G_{i-1}^{1*}] ),
$$

where $*$ denotes values output by decoder2.  I want to know if this implementation is equivalent to the formulation in the paper. How should I understand it?

**Comment by yocabon** [comment]
Hi, the code you're point at is just a trick to avoid computing the encoder twice for the same image when we do img1, img2 and img2, img1

**Comment by wdkkkk** [comment]
Thanks! I understand it know.

**Comment by Gynjn** [comment]
@yocabon @wdkkkk Could you elaborate more details about it? Based on the comments, "if the decoder1 is responsible for view1 and decoder2 is responsible for the view2" then we can just use each features w/o interleave function.

For example if the batch size is 2 (A and B), after interleaving the feature becomes $[A_0, A_1, B_0, B_1]$ for decoder1 and $[A_1, A_0, B_1, B_0]$ for decoder2. So for the calculation with criterion on both decoders, we have to use combined ground truths (view1 and view2) for each decoder. (Saying, decoder1 is not only responsible for view1, it gets loss signal from both views (view1 and view2) and same operation is applied to decoder2.

Then, based on the reply, "a trick to avoid computing the encoder twice for the same image when we do img1, img2 and img2, img1" is meaning that using one iteration, train both settings (img1=view1, img2=view2) and (img2=view1, img1=view2) with one forward pass of encoder?

Thanks in advance.
