### ISSUE TITLE
scannetpp_pairs not compatible with scannetpp's colmap data

### ISSUE THREAD

**Issue by Jarrome** [naver/dust3r#159]
Nice work! 

I try to finetune on `scannetpp`, but got some problem on preprocess step using the provided pairs.

```
File "dust3r/datasets_preprocess/preprocess_scannetpp.py", line 267, in process_scenes
    imgidx = img_idx[imgname]
             ~~~~~~~^^^^^^^^^
KeyError: 'frame_004370.jpg'
```

The scene is `036bce3393`, I checked scannetpp which doesnot have this frame in `colmap/images.txt`

Do you know how to fix the mismatch of the data?
Does scannetpp updated somehow?

**Comment by yocabon** [comment]
Hi, discussions about this will be in https://github.com/naver/dust3r/issues/165
