### ISSUE TITLE
Table 1 discrepencies

### ISSUE THREAD

**Issue by kmatzen** [naver/dust3r#171]
Could I get some help understanding how table 1 in the paper was computed?  I tried to reproduce the results using the given [DUSt3R_ViTLarge_BaseDecoder_512_dpt](https://download.europe.naverlabs.com/ComputerVision/DUSt3R/DUSt3R_ViTLarge_BaseDecoder_512_dpt.pth) model and a model that I newly trained using the provided code.  I started by comparing the two models with visloc.py on the 7-scenes dataset, but the numbers for the provided model don't seem to match what is reported in the paper.

| Subscene     | Variant | Images | Median Pos Error | Median Angular Error | acc@0.1m,1deg | acc@0.25m,2deg | acc@0.5m,5deg | acc@5m,10deg |
|--------------|---------|--------|-----------------|----------------------|---------------|----------------|---------------|--------------|
| chess        | Given   | 2000   | 0.08876         | 2.79708              | 2.85          | 29.05          | 91.00         | 98.45        |
| chess        | Mine    | 2000   | 0.08291         | 2.92299              | 3.95          | 27.90          | 88.95         | 98.45        |
| fire         | Given   | 2000   | 0.05118         | 1.92276              | 21.25         | 51.65          | 90.50         | 98.10        |
| fire         | Mine    | 2000   | 0.05716         | 2.22613              | 18.45         | 45.20          | 91.00         | 99.25        |
| heads        | Given   | 1000   | 0.02548         | 1.55556              | 27.90         | 64.70          | 90.20         | 92.20        |
| heads        | Mine    | 1000   | 0.03809         | 2.14186              | 13.50         | 45.50          | 80.60         | 87.00        |
| office       | Given   | 4000   | 0.18812         | 4.79558              | 3.85          | 17.58          | 51.63         | 63.53        |
| office       | Mine    | 4000   | 0.21497         | 5.31324              | 4.43          | 15.80          | 48.08         | 62.98        |
| pumpkin      | Given   | 2000   | 0.15922         | 3.88746              | 2.75          | 24.20          | 62.55         | 79.80        |
| pumpkin      | Mine    | 2000   | 0.16227         | 4.01992              | 4.20          | 24.60          | 57.00         | 77.70        |
| redkitchen   | Given   | 5000   | 0.12894         | 3.88511              | 3.84          | 21.10          | 60.48         | 80.38        |
| redkitchen   | Mine    | 5000   | 0.12973         | 3.53684              | 4.10          | 21.20          | 62.40         | 83.18        |
| stairs       | Given   | 1000   | inf             | inf                  | 1.50          | 7.30           | 17.10         | 18.90        |
| stairs       | Mine    | 1000   | inf             | inf                  | 0.50          | 2.60           | 8.00          | 10.90        |

The "given" results were computed with this command as an example.
```
python3 visloc.py \
  --dataset "VislocSevenScenes('/mnt/localssd/7scenes/', subscene='redkitchen', pairsfile='APGeM-LM18_top20', topk=1)" \
  --pnp_mode poselib \
  --reprojection_error_diag_ratio 0.008 \
  --output_dir /mnt/localssd/7scenes/redkitchen/loc-given_poselib_stage3 \
  --model_name DUSt3R_ViTLarge_BaseDecoder_512_dpt
```

<img width="963" alt="Screenshot 2024-08-30 at 11 58 21 AM" src="https://github.com/user-attachments/assets/5e36c01f-52c4-40d1-90e5-b3598f31996f">

**Comment by yocabon** [comment]
Hi, I do not get the same results as you, so I am not sure what's going on.

```
python3 visloc.py --model_name DUSt3R_ViTLarge_BaseDecoder_512_dpt --dataset "VislocSevenScenes('/path/to/7-scenes/', subscene='chess', pairsfile='APGeM-LM18_top20', topk=1)" --pnp_mode poselib --reprojection_error_diag_ratio 0.008 --output_dir /path/to/dust3r_7scenes/20_09_24/chess/loc 
```
gives me 
```
VislocSevenScenes('/path/to/7-scenes/', subscene='chess', pairsfile='APGeM-LM18_top20', topk=1): 2000 images - median_pos_error=0.027831130071196423, median_angular_error=0.9597363623122772  - acc@0.1m,1deg=53.050  - acc@0.25m,2deg=89.400  - acc@0.5m,5deg=97.700  - acc@5m,10deg=97.750
```

**Comment by kmatzen** [comment]
Would it be possible for you to share some preprocessed data as per https://github.com/naver/dust3r/tree/main/dust3r_visloc#7scenes?  Then I could see if there's a problem with how I followed the preprocessing instructions or if there's a problem with how the model is used.

**Comment by kmatzen** [comment]
I reprocessed the chess dataset and now get results similar to yours.  It seems like something might have gone wrong with the extract_kapture.py stage, but I'm not sure what.  The checkpoint is not corrupt.  But the gfeats changed between runs.

**Comment by kmatzen** [comment]
For completeness, here's the updated table.  I didn't look into why the stairs dataset has a problem.

| Subscene    | Images | Model (Mine/Given) | Median Pos Error       | Median Angular Error    | acc@0.1m,1deg | acc@0.25m,2deg | acc@0.5m,5deg | acc@5m,10deg |
|-------------|--------|--------------------|------------------------|-------------------------|---------------|----------------|---------------|--------------|
| pumpkin     | 2000   | Mine               | 0.042586690970645616    | 1.110084831203734        | 39.950        | 76.650         | 93.500        | 96.250       |
| pumpkin     | 2000   | Given              | 0.042014010823642256    | 1.122741417611579        | 40.800        | 78.250         | 96.700        | 99.000       |
| chess       | 2000   | Mine               | 0.033120336061303796    | 1.1075863185699586       | 42.150        | 86.800         | 98.500        | 99.300       |
| chess       | 2000   | Given              | 0.02804392177381982     | 0.9694177466688886       | 52.550        | 88.800         | 97.550        | 97.600       |
| office      | 4000   | Mine               | 0.03786934465919008     | 1.0163818152595911       | 48.975        | 89.325         | 99.350        | 99.675       |
| office      | 4000   | Given              | 0.03433584698302677     | 0.9915453956437292       | 50.450        | 88.350         | 99.125        | 99.375       |
| fire        | 2000   | Mine               | 0.033405749492337086    | 1.109990355159503        | 44.100        | 81.200         | 95.800        | 98.250       |
| fire        | 2000   | Given              | 0.02754007835928138     | 1.0249349073713077       | 48.750        | 82.750         | 94.250        | 95.350       |
| stairs      | 1000   | Mine               | inf                    | inf                      | 2.400         | 9.200          | 23.400        | 25.900       |
| stairs      | 1000   | Given              | inf                    | inf                      | 4.500         | 13.900         | 22.800        | 24.300       |
| heads       | 1000   | Mine               | 0.020320863216878725    | 1.2609868297391646       | 39.800        | 72.800         | 95.400        | 96.700       |
| heads       | 1000   | Given              | 0.015424411078463426    | 1.1095268143484076       | 44.400        | 76.200         | 91.600        | 92.200       |
| redkitchen  | 5000   | Mine               | 0.042633941272723234    | 1.3796650352310644       | 31.780        | 71.060         | 97.220        | 99.740       |
| redkitchen  | 5000   | Given              | 0.040518418574675016    | 1.3350243578985486       | 33.680        | 73.960         | 97.600        | 99.720       |


@Archer-204, here are my notes.
I had to create a separate environment with python3.8 and scikit-learn 0.23.2 to get Resnet101-AP-GeM-LM18.pt to load.

```
conda create -n deep-image-retrieval python=3.8
conda activate deep-image-retrieval
cd ../kapture
pip install -r requirements.txt
conda install pytorch torchvision torchaudio pytorch-cuda=11.8 -c pytorch -c nvidia

conda install scikit-learn==0.23.2 "numpy<=1.23"

CUDA_VISIBLE_DEVICES=0 python3 ./dirtorch/extract_kapture.py --kapture-root /mnt/localssd/dust3r_debug/7-scenes/chess/mapping/ --checkpoint Resnet101-AP-GeM-LM18.pt --gpu 0

CUDA_VISIBLE_DEVICES=0 python3 ./dirtorch/extract_kapture.py --kapture-root /mnt/localssd/dust3r_debug/7-scenes/chess/query/ --checkpoint Resnet101-AP-GeM-LM18.pt --gpu 0

cd ..
git clone https://github.com/naver/kapture-localization.git
cd kapture-localization
pip install -r requirements.txt
python3 tools/kapture_compute_image_pairs.py --mapping ../7-scenes/chess/mapping/ --query ../7-scenes/chess/query/ -o ../7-scenes/chess/pairsfile/query/APGeM-LM18_top20.txt
```

Also note that there's a typo in one script that attempts to find the file in `pairfiles` instead of `pairsfile`.  Finally, when you run visloc.py, it might report "error for pnp" for each query.  You likely need to install `poselib`.
