### ISSUE TITLE
Per-scene MVS metrics on DTU dataset

### ISSUE THREAD

**Issue by Hippogriff** [naver/dust3r#174]
Can you please provide per-scene metrics on DTU dataset for MVS experiments?

**Comment by vincent-leroy** [comment]
Hi,
Here you are:
  | accuracy | completeness | overall
-- | -- | -- | --
scan10 | 2.373 | 0.525 | 1.449
scan110 | 3.150 | 0.710 | 1.930
scan114 | 3.305 | 0.744 | 2.024
scan118 | 4.190 | 1.336 | 2.763
scan11 | 1.423 | 0.587 | 1.005
scan12 | 1.503 | 0.428 | 0.966
scan13 | 1.015 | 0.409 | 0.712
scan15 | 1.592 | 0.610 | 1.101
scan1 | 1.205 | 0.468 | 0.836
scan23 | 2.047 | 1.013 | 1.530
scan24 | 2.578 | 0.779 | 1.679
scan29 | 2.256 | 0.995 | 1.626
scan32 | 3.828 | 0.846 | 2.337
scan33 | 2.082 | 0.639 | 1.361
scan34 | 1.828 | 0.635 | 1.231
scan48 | 4.057 | 1.015 | 2.536
scan49 | 3.668 | 1.607 | 2.638
scan4 | 2.722 | 0.835 | 1.778
scan62 | 3.218 | 1.065 | 2.141
scan75 | 3.866 | 0.652 | 2.259
scan77 | 4.694 | 0.900 | 2.797
scan9 | 1.983 | 0.640 | 1.311
