### ISSUE TITLE
COLMAP reconstruction for Cambridge Landmark?

### ISSUE THREAD

**Issue by ahmed-akader** [naver/dust3r#179]
Could you please provide the commands to generate the COLMAP reconstructions?  Those files are not included in the original dataset, and there are no instructions to generate them as indicated for other files. 

I'm referring to the doc here, which assumes Cambridge Landmark directories follow a certain format: https://github.com/naver/dust3r/tree/main/dust3r_visloc#cambridgelandmarks

**Comment by yocabon** [comment]
Hi,
please take a look at this issue: https://github.com/naver/mast3r/issues/20

In particular, comments about https://github.com/naver/kapture-localization/blob/main/pipeline/examples/run_cambridge.sh
(we used RETRIEVAL_TOPK=50 for mapping)

**Comment by ahmed-akader** [comment]
Thanks for the pointers.  I was able to follow the steps in the `run_cambridge.sh` script.

FYI - there seems to be a few issues with the `run_cambridge.sh` script as is:
- it gets stuck in `${TMP_DIR}`  after it's done downloading files
- it suggests I can select `WORKING_DIR` as I please, though it may be necessary to provide the absolute path
- it defaults to wanting to delete downloaded files, which didn't help while debugging
- the pip command forces older package versions, seemingly unnecessarily (I was able to use the environment I prepared earlier for [deep-image-retrieval](https://github.com/naver/deep-image-retrieval), which the script ends up needing anyway)
