### ISSUE TITLE
Getting the point clouds out at the right scale

### ISSUE THREAD

**Issue by truncs** [naver/dust3r#44]
Would it be possible to use spase or dense matchers to get the scale out? Getting all the matched points and then using the known intrinsics to project them into 3d and then comparing the same points to pointmap in dust3r?

**Comment by truncs** [comment]
@vincent-leroy Thanks for the prompt reply!
Would it work if get the matched sampled points from stereo images with known baseline? 
Are there plans to train a metric DUSt3R and release it?

**Comment by vincent-leroy** [comment]
I guess it should work if you find the right transformation to align to whatever metric prediction you have. 
We plan it for the next release yes

**Comment by rust-in** [comment]
Hi @vincent-leroy, thank you for your great work!

Do you still have any plans to release a metric DUSt3R?
