### ISSUE TITLE
Can I export *.glb/*.ojb file from dust3R by a python script?

### ISSUE THREAD

**Issue by zhongqiu1245** [naver/dust3r#57]
Hello
Thank you for your amazing job!
Can I export *.glb/*.ojb file by dust3R? (for example, with your script 'Usage' in your readme)
If it is right, how can I export?
Thank you in advance!

**Comment by zhongqiu1245** [comment]
or exporting *.ply/*.pcd

**Comment by yocabon** [comment]
Hi,
did you check how we're doing it in `demo.py` ?

see https://github.com/naver/dust3r/blob/main/demo.py#L91 and https://github.com/naver/dust3r/blob/main/demo.py#L49

**Comment by zhongqiu1245** [comment]
Thanks！
