### ISSUE TITLE
Wrong Intrinsics

### ISSUE THREAD

**Issue by zjrandom951** [naver/dust3r#64]
There seems to be an issue with the camera's intrinsics, some focal is 0.

**Comment by zjrandom951** [comment]
img

**Comment by zjrandom951** [comment]
screenshot

**Comment by zjrandom951** [comment]
gti['camera intrinsics']
tensor([[[ 0.0000，517.1331，255.8754],
[517.1331,
0.0000, 79.5000],
0.0000,
0.0000.
1.0000]]
[[ 0.0000，521.7863， 255.8768].
521.7863
80.2061]，
o.0ooo.
[0.0000,
0.0000,
1.0000]].
0.0000，256.0131]
[[397.7553，
[0.0000，397.7553,
80.0000],
[0.0000,
[[402.5104,
0.0000.
1.0000]].
0.0000，255.5141]
[0.0000，402.5104,
80.0000],
[0.000o,
.0ooo.
1.0000]].
[[ 0.0000，523.6014，255.3805].
[523.6014,
[0.0000,
0.0000,79.5000].
1.0000]],
0.000日，
[[ 0.0000，518.5634，256.0831],
[518.5634,0.0000, 79.5000],
[0.0000,
0.0000.
1.0000]]],device='cuda:o')

**Comment by vincent-leroy** [comment]
We never encountered this before, could you provide a minimal example to reproduce please?

**Comment by zjrandom951** [comment]
![image](https://github.com/naver/dust3r/assets/67944280/85d29714-0dde-4d54-a4a6-06b469b6959c)
![image](https://github.com/naver/dust3r/assets/67944280/09001713-766c-46b6-9db2-f58f8ed3f38a)

when i try to run the training script, if the image resulotion is not square, then there is a probability that the diagonal element of the camera's intrinsics matrix is 0

**Comment by zjrandom951** [comment]
thanks, it should be because the image was traansposed.
