### ISSUE TITLE
Pretrained Croco

### ISSUE THREAD

**Issue by sailor-z** [naver/dust3r#65]
Hi,

Thanks a lot for the amazing work. Did you use the pretrained Croco model when training Dust3r? If so, could you please point out where you load the model in the training code? 

Thanks in advance!

**Comment by jerome-revaud** [comment]
yes
https://github.com/naver/dust3r/blob/82748a9f663f436c6290e151b23273d57708f07b/train.py#L45
https://github.com/naver/dust3r/blob/82748a9f663f436c6290e151b23273d57708f07b/train.py#L138

**Comment by sailor-z** [comment]
Thanks a lot!
