### ISSUE TITLE
demo.py does not output any scene in GUI when using scene_graph_type = "pairs" in demo.py

### ISSUE THREAD

**Issue by bhuvanjhamb** [naver/dust3r#69]
I am attempting to use using `scene_graph_type = "pairs"` in demo.py. In doing so, the GUI gets stuck and does not output any scene. After investigation, it seems like [this while loop](https://github.com/naver/dust3r/blob/5b3fb8f8230a8f827c5c569f6f2e79d1cb1f58df/dust3r/cloud_opt/init_im_poses.py#L150
)  gets stuck in an infinite loop.

I believe happens because each vertex is only one 1 edge in "pairs" setting, hence the while loop in this function never terminates.
This can be mitigated by updating the loop counter [here](https://github.com/naver/dust3r/blob/5b3fb8f8230a8f827c5c569f6f2e79d1cb1f58df/dust3r/image_pairs.py#L32C1-L35C47
) as follows:

```
# for i in range(0, len(imgs), 2):
#     pairs.append((imgs[i], imgs[i + 1]))

for i in range(0, len(imgs)-1, 1):
    pairs.append((imgs[i], imgs[i + 1]))
```

I am not sure is this is an bug or intended behavior, but let me know if you require a PR.

**Comment by yocabon** [comment]
Hi,
Thanks for the issue. Yes, it seems bugged.
I don't see any benefit over the "swin" strategy with winsize=1; so if it's ok, I'll just remove it.
