### ISSUE TITLE
when using swin in making pair, imgs will be maken pair with themselves

### ISSUE THREAD

**Issue by DissipativeStructureObject** [naver/dust3r#73]
in dust3r/image_pairs, about line 22
![AE2}%N8F_LKZ~WXT6J{YUPM](https://github.com/naver/dust3r/assets/38503930/95ae90e5-9534-4b81-9ce3-8746cd68c08a)
This can make j=0 in every loop, and then make idx=i.
Finally, every img[i] will have a pair (img[i], img[i]) which is unnecessary and is harmful to final cloud point.

Maybe
`for j in range(1, winsize):`
will be more appropriate.

**Comment by yocabon** [comment]
Hi, thanks for the issue, it should be fixed now.
