### ISSUE TITLE
TypeError: AsymmetricCroCo3DStereo.__init_subclass__() takes no keyword arguments

### ISSUE THREAD

**Issue by chengluberkeley** [naver/dust3r#80]
I sync to the latest commit of the repo, and follow the code in the "Usage" part of ReadMe. However, for
`from dust3r.model import AsymmetricCroCo3DStereo`, I get the below error:

`TypeError: AsymmetricCroCo3DStereo.__init_subclass__() takes no keyword arguments`

How to resolve it? Thanks.

**Comment by yocabon** [comment]
Hi, it should be caused by an incompatible version of the huggingface_hub dependency. I added a version check in the code with a more verbose error message.

Can you update it ?

either
`pip install -r requirements.txt`
or 
`pip install huggingface-hub[torch]>=0.22`

**Comment by chengluberkeley** [comment]
It works. Thanks!
