### ISSUE TITLE
Monocular Depth Estimation

### ISSUE THREAD

**Issue by Davidyao99** [naver/dust3r#82]
I am trying to use Dust3r to obtain depth maps for a single image. I fed in the same image twice into the model for inference. I was expecting the pts3d from pred1 and pts3d_in_other_view from pred2 to match, but it appears that there is a non-zero difference between the two predictions (difference is of the order 1e-3, with actual values in the order of 1e-1). 

Is this expected behavior? And if so, should I just take the output from pred1 as the depth? or average the two results to get a better depth estimation?

Thanks and great work!

**Comment by yocabon** [comment]
Hi,
It's not surprising -> we didn't train it for this. The prediction for img1 is usually more accurate than the one for img2, so it should be better to just take the output from pred1.

**Comment by puyiwen** [comment]
@yocabon sorry to bother you, the depth output of the model, is it metric depth?

**Comment by davnords** [comment]
@puyiwen no it is not metric, it is normalized I believe. MASt3R includes a metric loss, use that instead
