### ISSUE TITLE
Question with “dust3r/dust3r/cloud_opt/base_opt.py” ？

### ISSUE THREAD

**Issue by wqx854987945** [naver/dust3r#97]
Hello! There's a problem here that's bothering me:
in dust3r/dust3r/cloud_opt/base_opt.py
`pw_poses = self.get_pw_poses() 
def get_pw_poses(self):  # cam to world
        RT = self._get_poses(self.pw_poses)
        scaled_RT = RT.clone()
        scaled_RT[:, :3] *= self.get_pw_scale().view(-1, 1, 1)  # scale the rotation AND translation
        return scaled_RT`
Why are the r and t multiplied by scale? In general, isn't the scaling factor only multiplied by t？

**Comment by noamelata** [comment]
Is this solved?
